# -*- coding: utf-8 -*-
"""PROJEK BIG DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmEb2wxYSNYCo9q3If9YFce174GVvwmh
"""

from collections import deque
import time

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import requests
import streamlit as st

st.set_page_config(
    page_title="Sky Watch | Deteksi Anomali Pesawat",
    page_icon="✈️",
    layout="wide",
)

st.title("✈️ Sky Watch | Deteksi Anomali Kecepatan & Ketinggian Pesawat")
st.caption(
    "Data real-time dari OpenSky Network (API gratis). Mendeteksi pesawat dengan "
    "kecepatan/ketinggian tidak wajar lewat kombinasi pola: batas fisik+durasi, "
    "lonjakan mendadak, squawk darurat, dan absence. Semua ditulis langsung di "
    "Python/pandas."
)

st.sidebar.header("⚙️ Pengaturan Dashboard")

st.sidebar.subheader("🗺️ Area Pantauan (Bounding Box)")
LAMIN = st.sidebar.number_input("Lintang minimum", min_value=-90.0, max_value=90.0, value=-9.5, step=0.5)
LAMAX = st.sidebar.number_input("Lintang maksimum", min_value=-90.0, max_value=90.0, value=-5.0, step=0.5)
LOMIN = st.sidebar.number_input("Bujur minimum", min_value=-180.0, max_value=180.0, value=105.0, step=0.5)
LOMAX = st.sidebar.number_input("Bujur maksimum", min_value=-180.0, max_value=180.0, value=116.0, step=0.5)

POLL_SECONDS = st.sidebar.number_input(
    "Interval Update (Detik)", min_value=10, max_value=600, value=60,
    help="API anonim OpenSky punya kuota harian dan resolusi data sekitar 10 detik. Jangan terlalu kecil."
)
MAX_SNAPSHOT = st.sidebar.number_input("Max Snapshot di Buffer", min_value=5, max_value=200, value=30)

st.sidebar.markdown("---")
st.sidebar.subheader("🚨 Batas Wajar Pesawat")
MAX_SPEED_KMH = st.sidebar.number_input("Kecepatan maksimum (km/jam)", min_value=800, max_value=1500, value=1000)
MAX_ALT_M = st.sidebar.number_input("Ketinggian maksimum (m)", min_value=10000, max_value=20000, value=15000)
MIN_SPEED_KMH = st.sidebar.number_input(
    "Kecepatan minimum di ketinggian tinggi (km/jam)", min_value=50, max_value=400, value=200,
    help="Pesawat yang terbang di atas ketinggian tertentu tapi lebih lambat dari ini dianggap janggal (mendekati stall)."
)
MIN_ALT_FOR_MINSPEED = st.sidebar.number_input("Syarat ketinggian untuk batas minimum (m)", min_value=1000, max_value=10000, value=5000)
Z_THRESH = st.sidebar.slider(
    "Ambang Robust Z-Score (antar pesawat)", min_value=2.0, max_value=6.0, value=3.5, step=0.1,
    help="Dihitung hanya untuk pesawat di ketinggian jelajah (>= 8000 m) pada snapshot yang sama."
)

st.sidebar.markdown("---")
st.sidebar.subheader("🧩 Parameter Pola")
MIN_CONSECUTIVE = st.sidebar.number_input(
    "Batas Fisik: min. snapshot beruntun", min_value=1, max_value=10, value=2,
    help="Anomali baru dianggap valid kalau bertahan minimal segini snapshot berturut-turut pada pesawat yang sama."
)
MAX_ACCEL = st.sidebar.number_input(
    "Lonjakan: percepatan maks (m/s²)", min_value=1.0, max_value=30.0, value=5.0, step=0.5,
    help="Perubahan kecepatan per detik antar dua snapshot."
)
MAX_ALT_RATE = st.sidebar.number_input(
    "Lonjakan: laju naik/turun maks (m/s)", min_value=10.0, max_value=200.0, value=50.0, step=5.0,
    help="Perubahan ketinggian per detik antar dua snapshot (50 m/s ≈ 10.000 ft/menit)."
)
ABSENCE_TOLERANCE = st.sidebar.slider(
    "Absence: toleransi (x interval update)", min_value=1.5, max_value=10.0, value=3.0, step=0.5,
    help="Alert 'data hilang' menyala jika tidak ada snapshot baru selama lebih dari toleransi x interval update."
)

is_running = st.sidebar.toggle("Jalankan Real-Time Update", value=True)

if st.sidebar.button("🔄 Reset / Reload Data"):
    st.session_state.clear()
    st.rerun()

OPENSKY_URL = "https://opensky-network.org/api/states/all"
STATE_COLUMNS = [
    "icao24", "callsign", "origin_country", "time_position", "last_contact",
    "longitude", "latitude", "baro_altitude", "on_ground", "velocity",
    "true_track", "vertical_rate", "sensors", "geo_altitude", "squawk",
    "spi", "position_source",
]
SQUAWK_DARURAT = {"7500": "pembajakan", "7600": "radio mati", "7700": "darurat umum"}


def fetch_states(lamin, lomin, lamax, lomax):
    """Mengambil 1 snapshot posisi semua pesawat di dalam bounding box.
    Mengembalikan (DataFrame, pesan_error). DataFrame = None jika request gagal."""
    params = {"lamin": lamin, "lomin": lomin, "lamax": lamax, "lomax": lomax}
    try:
        resp = requests.get(OPENSKY_URL, params=params, timeout=20)
        if resp.status_code == 429:
            return None, "Rate limit OpenSky tercapai (HTTP 429). Perbesar interval update atau kecilkan area."
        resp.raise_for_status()
        payload = resp.json()
    except Exception as e:
        return None, f"Gagal mengambil data OpenSky: {e}"

    states = payload.get("states")
    if not states:
        return pd.DataFrame(), None

    raw = pd.DataFrame(states).iloc[:, :len(STATE_COLUMNS)]
    raw.columns = STATE_COLUMNS

    raw["callsign"] = raw["callsign"].astype(str).str.strip().replace({"": np.nan, "None": np.nan})
    raw["label"] = raw["callsign"].fillna(raw["icao24"])
    raw["timestamp"] = pd.to_datetime(payload["time"], unit="s", utc=True)
    raw["alt_m"] = pd.to_numeric(raw["baro_altitude"], errors="coerce").fillna(
        pd.to_numeric(raw["geo_altitude"], errors="coerce")
    )
    raw["speed_ms"] = pd.to_numeric(raw["velocity"], errors="coerce")
    raw["speed_kmh"] = raw["speed_ms"] * 3.6

    df = raw[raw["on_ground"] == False]  # hanya pesawat yang sedang terbang
    df = df.dropna(subset=["alt_m", "speed_ms", "longitude", "latitude"])
    return df[[
        "timestamp", "icao24", "label", "origin_country", "longitude", "latitude",
        "alt_m", "speed_ms", "speed_kmh", "squawk",
    ]].reset_index(drop=True), None

def consecutive_true_count(mask: pd.Series) -> pd.Series:
    """Panjang 'streak' True berturut-turut yang berakhir di tiap baris.
    [F,T,T,T,F,T] -> [0,1,2,3,0,1]. Dipakai untuk pola Batas Fisik+Durasi."""
    counts = np.zeros(len(mask), dtype=int)
    running = 0
    for i, v in enumerate(mask.to_numpy()):
        running = running + 1 if v else 0
        counts[i] = running
    return pd.Series(counts, index=mask.index)


def robust_z(s: pd.Series, min_n: int = 5) -> pd.Series:
    """Z-score robust (median & MAD) sehingga tidak mudah terdistorsi oleh outlier.
    Jika pesawat terlalu sedikit atau MAD = 0, dianggap tidak ada penyimpangan."""
    if s.notna().sum() < min_n:
        return pd.Series(0.0, index=s.index)
    med = s.median()
    mad = (s - med).abs().median()
    if pd.isna(mad) or mad == 0:
        return pd.Series(0.0, index=s.index)
    return 0.6745 * (s - med) / mad


def analyze_buffer(buffer_data, max_speed, max_alt, min_speed, min_alt_for_speed,
                   z_thresh, max_accel, max_alt_rate, min_consecutive):
    """Menghitung fitur per pesawat + 3 pola deteksi di atasnya."""
    frames = list(buffer_data)
    if not frames:
        return pd.DataFrame()

    df = pd.concat(frames, ignore_index=True)
    df = (df.sort_values(["icao24", "timestamp"])
            .drop_duplicates(["icao24", "timestamp"])
            .reset_index(drop=True))

    # --- Perubahan antar snapshot untuk tiap pesawat ---
    g = df.groupby("icao24")
    dt = g["timestamp"].diff().dt.total_seconds()
    dt = dt.where((dt > 0) & (dt <= 300))  # abaikan jeda terlalu panjang
    df["accel"] = g["speed_ms"].diff() / dt        # m/s^2
    df["alt_rate"] = g["alt_m"].diff() / dt        # m/s

    # --- Z-score kecepatan antar pesawat di ketinggian jelajah (per snapshot) ---
    cruise = df["alt_m"] >= 8000
    df["z_speed"] = np.nan
    if cruise.any():
        df.loc[cruise, "z_speed"] = (
            df[cruise].groupby("timestamp")["speed_kmh"].transform(robust_z)
        )

    # POLA 1 — Batas Fisik + Durasi
    df["speed_high"] = df["speed_kmh"] > max_speed
    df["alt_high"] = df["alt_m"] > max_alt
    df["speed_low"] = (df["speed_kmh"] < min_speed) & (df["alt_m"] >= min_alt_for_speed)
    df["z_anomaly"] = df["z_speed"].abs() > z_thresh
    df["state_raw"] = df[["speed_high", "alt_high", "speed_low", "z_anomaly"]].any(axis=1)
    df["streak"] = df.groupby("icao24")["state_raw"].transform(consecutive_true_count)
    df["state_pattern"] = df["streak"] >= min_consecutive

    # POLA 2 — Lonjakan Mendadak (event sesaat, tidak perlu durasi)
    df["accel_high"] = df["accel"].abs() > max_accel
    df["rate_high"] = df["alt_rate"].abs() > max_alt_rate
    df["jump_pattern"] = df["accel_high"] | df["rate_high"]

    # POLA 3 — Squawk Darurat
    df["emergency_pattern"] = df["squawk"].isin(list(SQUAWK_DARURAT.keys()))

    df["anomaly"] = df["state_pattern"] | df["jump_pattern"] | df["emergency_pattern"]
    return df


def compute_absence_alert(last_timestamp, poll_seconds, tolerance):
    """POLA 4 — Absence: tidak ada snapshot baru dalam window yang diharapkan."""
    if last_timestamp is None:
        return False, 0.0
    now = pd.Timestamp.now(tz=last_timestamp.tzinfo) if last_timestamp.tzinfo else pd.Timestamp.now()
    gap = (now - last_timestamp).total_seconds()
    return gap > poll_seconds * tolerance, gap


def build_event_log(df, max_rows=30):
    """Mengumpulkan semua pola yang terdeteksi jadi satu log event."""
    cols = ["timestamp", "pesawat", "pola", "deskripsi"]
    if df.empty or not df["anomaly"].any():
        return pd.DataFrame(columns=cols)

    events = []
    for _, row in df[df["anomaly"]].iterrows():
        base = {"timestamp": row["timestamp"], "pesawat": row["label"]}

        if row["state_pattern"]:
            alasan = []
            if row["speed_high"]:
                alasan.append(f"kecepatan {row['speed_kmh']:,.0f} km/jam melebihi batas")
            if row["alt_high"]:
                alasan.append(f"ketinggian {row['alt_m']:,.0f} m melebihi batas")
            if row["speed_low"]:
                alasan.append(f"kecepatan {row['speed_kmh']:,.0f} km/jam terlalu rendah untuk ketinggian {row['alt_m']:,.0f} m")
            if row["z_anomaly"]:
                alasan.append(f"kecepatan menyimpang dari pesawat lain (z={row['z_speed']:.1f})")
            events.append({**base, "pola": "Batas Fisik+Durasi",
                           "deskripsi": "; ".join(alasan) + f" — {int(row['streak'])}x beruntun"})

        if row["jump_pattern"]:
            alasan = []
            if row["accel_high"]:
                alasan.append(f"percepatan {row['accel']:+.1f} m/s²")
            if row["rate_high"]:
                alasan.append(f"laju vertikal {row['alt_rate']:+.1f} m/s")
            events.append({**base, "pola": "Lonjakan Mendadak",
                           "deskripsi": "Perubahan tidak wajar antar snapshot: " + ", ".join(alasan)})

        if row["emergency_pattern"]:
            events.append({**base, "pola": "Squawk Darurat",
                           "deskripsi": f"Squawk {row['squawk']} ({SQUAWK_DARURAT[row['squawk']]})"})

    log = pd.DataFrame(events).sort_values("timestamp", ascending=False)
    return log.head(max_rows).reset_index(drop=True)

if "buffer" not in st.session_state:
    st.session_state.buffer = deque(maxlen=MAX_SNAPSHOT)
    st.session_state.last_fetch = 0.0
    st.session_state.last_error = None

# Fetch dibatasi oleh interval, supaya interaksi widget tidak menghabiskan kuota API
elapsed = time.time() - st.session_state.last_fetch
if st.session_state.last_fetch == 0.0 or (is_running and elapsed >= POLL_SECONDS):
    with st.spinner("Mengambil data OpenSky..."):
        df_new, err = fetch_states(LAMIN, LOMIN, LAMAX, LOMAX)
    st.session_state.last_fetch = time.time()
    st.session_state.last_error = err
    if df_new is not None and not df_new.empty:
        buf = st.session_state.buffer
        if len(buf) == 0 or buf[-1]["timestamp"].iloc[0] != df_new["timestamp"].iloc[0]:
            buf.append(df_new)

df_analyzed = analyze_buffer(
    st.session_state.buffer, MAX_SPEED_KMH, MAX_ALT_M, MIN_SPEED_KMH,
    MIN_ALT_FOR_MINSPEED, Z_THRESH, MAX_ACCEL, MAX_ALT_RATE, MIN_CONSECUTIVE
)

"""# DASHBOARD"""

if st.session_state.last_error:
    st.warning(f"⚠️ {st.session_state.last_error}")

if not df_analyzed.empty:
    last_ts = df_analyzed["timestamp"].max()
    current = df_analyzed[df_analyzed["timestamp"] == last_ts]
    is_absent, gap_seconds = compute_absence_alert(last_ts, POLL_SECONDS, ABSENCE_TOLERANCE)

    if is_absent:
        st.error(
            f"🛑 **Pola Absence terdeteksi** — tidak ada snapshot baru selama "
            f"{gap_seconds:,.0f} detik (toleransi: {POLL_SECONDS * ABSENCE_TOLERANCE:,.0f} detik). "
            "Kemungkinan API OpenSky bermasalah atau kuota habis."
        )
    if len(st.session_state.buffer) < 2:
        st.info("Baru 1 snapshot terkumpul. Deteksi lonjakan dan durasi butuh minimal 2 snapshot.")

    st.markdown("#### 📊 Statistik Terkini")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Pesawat Terlacak", f"{len(current):,}")
    c2.metric("Anomali Aktif", f"{int(current['anomaly'].sum()):,}")
    c3.metric("Median Kecepatan", f"{current['speed_kmh'].median():,.0f} km/jam")
    c4.metric("Median Ketinggian", f"{current['alt_m'].median():,.0f} m")
    c5.metric("Snapshot di Buffer", f"{len(st.session_state.buffer)}")

    st.markdown("#### 🧩 Status Pola Deteksi")
    p1, p2, p3, p4 = st.columns(4)
    with p1:
        st.write("**Batas Fisik + Durasi**")
        n = int(current["state_pattern"].sum())
        st.error(f"⚠️ {n} pesawat di luar batas wajar") if n else st.success("✅ Normal")
    with p2:
        st.write("**Lonjakan Mendadak**")
        n = int(current["jump_pattern"].sum())
        st.warning(f"📈 {n} pesawat berubah drastis") if n else st.success("✅ Tidak ada lonjakan")
    with p3:
        st.write("**Squawk Darurat**")
        n = int(current["emergency_pattern"].sum())
        st.error(f"🚨 {n} pesawat squawk darurat") if n else st.success("✅ Tidak ada squawk darurat")
    with p4:
        st.write("**Absence**")
        if is_absent:
            st.error(f"🛑 Data hilang {gap_seconds:,.0f}s")
        else:
            st.success(f"✅ Update {gap_seconds:,.0f}s lalu")

    st.markdown("---")

    # -----------------------------------------------------
    # Grafik: profil kecepatan-ketinggian (kiri) dan peta posisi (kanan)
    # -----------------------------------------------------
    normal = current[~current["anomaly"]]
    anom = current[current["anomaly"]]

    col_a, col_b = st.columns(2)
    with col_a:
        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(x=normal["speed_kmh"], y=normal["alt_m"], mode="markers",
                                  name="Normal", text=normal["label"],
                                  marker=dict(color="#1f77b4", size=7, opacity=0.7),
                                  hovertemplate="%{text}<br>%{x:.0f} km/jam<br>%{y:.0f} m<extra></extra>"))
        if not anom.empty:
            fig1.add_trace(go.Scatter(x=anom["speed_kmh"], y=anom["alt_m"], mode="markers",
                                      name="Anomali", text=anom["label"],
                                      marker=dict(color="red", size=12, symbol="x"),
                                      hovertemplate="%{text}<br>%{x:.0f} km/jam<br>%{y:.0f} m<extra></extra>"))
        fig1.add_vline(x=MAX_SPEED_KMH, line_dash="dash", line_color="gray")
        fig1.add_hline(y=MAX_ALT_M, line_dash="dash", line_color="gray")
        fig1.update_layout(template="plotly_white", height=420, title="Profil Kecepatan vs Ketinggian",
                           xaxis_title="Kecepatan (km/jam)", yaxis_title="Ketinggian (m)",
                           margin=dict(l=20, r=20, t=50, b=20))
        st.plotly_chart(fig1, use_container_width=True)

    with col_b:
        fig2 = go.Figure()
        fig2.add_trace(go.Scattergeo(lon=normal["longitude"], lat=normal["latitude"], mode="markers",
                                     name="Normal", text=normal["label"],
                                     marker=dict(color="#1f77b4", size=5)))
        if not anom.empty:
            fig2.add_trace(go.Scattergeo(lon=anom["longitude"], lat=anom["latitude"], mode="markers",
                                         name="Anomali", text=anom["label"],
                                         marker=dict(color="red", size=11, symbol="x")))
        fig2.update_geos(lataxis_range=[LAMIN, LAMAX], lonaxis_range=[LOMIN, LOMAX],
                         showland=True, showcountries=True, resolution=50)
        fig2.update_layout(template="plotly_white", height=420, title="Posisi Pesawat",
                           margin=dict(l=20, r=20, t=50, b=20))
        st.plotly_chart(fig2, use_container_width=True)

    # -----------------------------------------------------
    # Riwayat satu pesawat (default: pesawat anomali pertama)
    # -----------------------------------------------------
    st.markdown("#### 🔍 Riwayat Pesawat")
    anom_labels = sorted(anom["label"].unique())
    other_labels = [l for l in sorted(df_analyzed["label"].unique()) if l not in anom_labels]
    pilih = st.selectbox("Pilih pesawat", anom_labels + other_labels)
    hist = df_analyzed[df_analyzed["label"] == pilih].sort_values("timestamp")

    fig3 = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.5, 0.5],
                         vertical_spacing=0.08, subplot_titles=(f"Kecepatan: {pilih}", "Ketinggian"))
    fig3.add_trace(go.Scatter(x=hist["timestamp"], y=hist["speed_kmh"], mode="lines+markers",
                              name="Kecepatan", line=dict(color="#1f77b4")), row=1, col=1)
    fig3.add_trace(go.Scatter(x=hist["timestamp"], y=hist["alt_m"], mode="lines+markers",
                              name="Ketinggian", line=dict(color="#ff7f0e")), row=2, col=1)
    hist_anom = hist[hist["anomaly"]]
    if not hist_anom.empty:
        fig3.add_trace(go.Scatter(x=hist_anom["timestamp"], y=hist_anom["speed_kmh"], mode="markers",
                                  name="Anomali", marker=dict(color="red", size=11, symbol="x")), row=1, col=1)
        fig3.add_trace(go.Scatter(x=hist_anom["timestamp"], y=hist_anom["alt_m"], mode="markers",
                                  showlegend=False, marker=dict(color="red", size=11, symbol="x")), row=2, col=1)
    fig3.add_hline(y=MAX_SPEED_KMH, line_dash="dash", line_color="gray", row=1, col=1)
    fig3.add_hline(y=MAX_ALT_M, line_dash="dash", line_color="gray", row=2, col=1)
    fig3.update_layout(template="plotly_white", height=480, margin=dict(l=20, r=20, t=50, b=20),
                       legend=dict(orientation="h", yanchor="bottom", y=1.05, xanchor="left", x=0))
    fig3.update_yaxes(title_text="km/jam", row=1, col=1)
    fig3.update_yaxes(title_text="meter", row=2, col=1)
    fig3.update_xaxes(title_text="Waktu (UTC)", row=2, col=1)
    st.plotly_chart(fig3, use_container_width=True)

    # -----------------------------------------------------
    # Event Pattern Log
    # -----------------------------------------------------
    st.markdown("#### 📜 Event Pattern Log")
    st.caption("Daftar semua kejadian anomali yang terdeteksi pada buffer saat ini (terbaru di atas).")
    event_log = build_event_log(df_analyzed, max_rows=30)
    if event_log.empty:
        st.info("Belum ada anomali yang terdeteksi pada buffer saat ini.")
    else:
        st.dataframe(event_log, use_container_width=True, hide_index=True)

    with st.expander("📄 Lihat Data Mentah Terakhir (10 Baris)", expanded=False):
        st.dataframe(df_analyzed.tail(10).round(4), use_container_width=True)

else:
    st.warning("Data belum tersedia. Periksa koneksi, bounding box, atau kuota API OpenSky.")

# ---------------------------------------------------------
# 8. Loop Auto-Refresh
# ---------------------------------------------------------
if is_running:
    time.sleep(POLL_SECONDS)
    st.rerun()
